from tkinter import *

class SecondView(Frame):

    def __init__(self, parent, controller):
        Frame.__init__(self, parent)
        self.grid_columnconfigure(0, weight=1)
        self.grid_columnconfigure(1, weight=1)
        self.grid_columnconfigure(2, weight=1)
        self.controller = controller
        self.amountToPayVar = DoubleVar()
        self.amountPaidVar = DoubleVar()
        self.ballanceVar = DoubleVar()
        self.changeVar = DoubleVar()
        self.createView()
        self.reset('<<ShowView>>')

    def createView(self):
        self.button1gr=Button(self, text="1 gr", justify=CENTER)
        self.button1gr.grid(row=0, column=0,sticky=N + E + W + S, padx=2, pady=2)
        self.button2gr=Button(self, text="2 gr", justify=CENTER)
        self.button2gr.grid(row=0, column=1,sticky=N + E + W + S, padx=2, pady=2)
        self.button5gr=Button(self, text="5 gr", justify=CENTER)
        self.button5gr.grid(row=0, column=2,sticky=N + E + W + S, padx=2, pady=2)
        self.button10gr=Button(self, text="10 gr", justify=CENTER)
        self.button10gr.grid(row=1, column=0,sticky=N + E + W + S, padx=2, pady=2)
        self.button20gr=Button(self, text="20 gr", justify=CENTER)
        self.button20gr.grid(row=1, column=1,sticky=N + E + W + S, padx=2, pady=2)
        self. button50gr=Button(self, text="50 gr", justify=CENTER)
        self.button50gr.grid(row=1, column=2,sticky=N + E + W + S, padx=2, pady=2)
        self.button1zl=Button(self, text="1 zl", justify=CENTER)
        self.button1zl.grid(row=2, column=0,sticky=N + E + W + S, padx=2, pady=2)
        self.button2zl=Button(self, text="2 zl", justify=CENTER)
        self.button2zl.grid(row=2, column=1,sticky=N + E + W + S, padx=2, pady=2)
        self.button5zl=Button(self, text="5 zl", justify=CENTER)
        self.button5zl.grid(row=2, column=2,sticky=N + E + W + S, padx=2, pady=2)
        self.button10zl=Button(self, text="10 zl", justify=CENTER)
        self.button10zl.grid(row=3, column=0,sticky=N + E + W + S, padx=2, pady=2)
        self.button20zl=Button(self, text="20 zl", justify=CENTER)
        self.button20zl.grid(row=3, column=1, sticky=N + E + W + S, padx=2, pady=2)
        self.button50zl=Button(self, text="50 zl", justify=CENTER)
        self.button50zl.grid(row=3, column=2, sticky=N + E + W + S, padx=2, pady=2)
        self.button100zl=Button(self, text="100 zl", justify=CENTER)
        self.button100zl.grid(row=4, column=0,sticky=N + E + W + S, padx=2, pady=2)
        self.button200zl=Button(self, text="200 zl", justify=CENTER)
        self.button200zl.grid(row=4, column=1,sticky=N + E + W + S, padx=2, pady=2)
        self.buttonCreditCard=Button(self, text="Zapłac karta", justify=CENTER)
        self.buttonCreditCard.grid(row=4, column=2, sticky=N + E + W + S, padx=2, pady=2)
        Label(self, text="Wpłacono:", justify=LEFT).grid(row=6, columnspan=2, sticky=N + E + W + S)
        Label(self, textvariable=self.amountPaidVar).grid(row=6, column=2, sticky=N + E + W + S)
        Label(self, text="Pozostało do zapłaty:", justify=LEFT).grid(row=7, columnspan=2, sticky=N + E + W + S)
        Label(self, textvariable=self.ballanceVar).grid(row=7, column=2, sticky=N + E + W + S)
        Label(self, text="Reszta:", justify=LEFT).grid(row=8, columnspan=2, sticky=N + E + W + S)
        Label(self, textvariable=self.changeVar).grid(row=8, column=2, sticky=N + E + W + S)

    def reset(self, event):
        self.changeVar.set(0)
        self.amountPaidVar.set(0)
        self.ballanceVar.set(self.amountToPayVar.get())